name: CustomMobs
version: '2.0-SNAPSHOT'
main: com.savage.custommobs.CustomMobs
api-version: '1.20'
authors: [SavageDev]
commands:
  custommob:
    description: Creates a custom mob with custom attributes
    aliases: createmob
    permission: custommob.create
    permission-message: You don't have permission to do this!

